version: '3.8'

services:
  db:
    build: .
    container_name: course-db
    restart: always
    ports:
      - '5432:5432'
    volumes:  
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
  

  dbtest:
    build: .
    container_name: test-db
    restart: always
    ports:
      - '5433:5432' 
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres