version: '3.8'

services:
  db:
    image: project-db:latest
    build: .
    container_name: course-db
    restart: always
    ports:
      - '5432:5432'
    volumes:  
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=coursedb
      